services:
  studify-1.10:
    build: ./
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: tayyab
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: tayyab
      ME_CONFIG_MONGODB_SERVER: mongo
volumes:
  mongo-data:
    driver: local
